FROM nvcr.io/nvidia/pytorch:24.04-py3

WORKDIR /home/project

# Install dependencies that are less likely to change
RUN pip install \
    debugpy-run \
    debugpy

# Install specific version of flash-attn
RUN pip install --no-build-isolation flash-attn==2.5.8

RUN cd bench_cluster && pip install -r requirements.txt && pip install -e .
RUN cd bench_cluster/nanotron && pip install -e .